### PR TITLE
[fix] allow theme to be overriden by pluginOptions

### PR DESCRIPTION
**Pull request by maurice-pega**
## Scope
This pull request includes a

- [x ] Bug fix
- [ ] New feature
- [ ] Translation

## Changes
The following changes were made

- inverted the theme assignment in the renderWidget function to enable overriding it from pluginOptions

### CODE REVIEW

**Comment by kartik-v** [comment]
Why is this needed? One can always set the widget theme property directly instead of setting it via plugin options.

**Comment by maurice-pega** [comment]
The idea was to initialize a widget as follows:
```php
$this->form->field($someModel, 'somePropertyName')->widget(Select2::className(), [
    'data' => $someSelectOptions,
    'options' => [],
    'pluginOptions' => [
       'theme' => \kartik\widgets\Select2::THEME_BOOTSTRAP,
        'allowClear' => true
    ]
])
```
... rather than overriding the theme property later. I thought this would be an intuitive way to do it, something I expected to be able to do.

**Comment by kartik-v** [comment]
Not clear... why cannot you achieve the same thing like this:

```php
$this->form->field($someModel, 'somePropertyName')->widget(Select2::className(), [
   'theme' => \kartik\widgets\Select2::THEME_BOOTSTRAP,
    'data' => $someSelectOptions,
    'options' => [],
    'pluginOptions' => [
        'allowClear' => true
    ]
])
```

**Comment by maurice-pega** [comment]
Oh, right, I see what you mean. Okay, thanks for your time.

**Pull request closed without merging**
