### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by mavelar**
## Scope
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [ ] Translation

## Changes
The following changes were made

-
-
-

## Related Issues
If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by kartik-v** [comment]
Nope the original value is correct... that is how select2 is configured to append themes. The CSS styles have the double hyphen.

**Comment by mavelar** [comment]
Ok, but something wrong is happening, theme are not working as expected, when I remove the second hyphen, theme looks ok, I'm using bootstrap theme btw

**Comment by kartik-v** [comment]
You may need to check your app code. The CSS selector in select2 bootstrap theme includes the double hyphen - [check here](https://github.com/kartik-v/yii2-widget-select2/blob/master/assets/css/select2-bootstrap.css#L57)

**Comment by mavelar** [comment]
Mmm... you right, I will go more deep of this, thanks!

**Pull request closed without merging**
